name: arkantranscripter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - python-telegram-bot
      - youtube-transcript-api
      - openai==1.50.2
      - python-dotenv==1.0.1
      - asyncio==3.4.3
